import React from 'react';
import { motion } from 'framer-motion';
import { ArrowRight, CalendarDays, Tag, UserRound } from 'lucide-react';
import Layout from '../components/Layout';
import PageHero from '../components/PageHero';
import posts from '../data/blog.json';

export default function Blog() {
  return <Layout><PageHero tagline="Latest News" title="Our" titleHighlight="Blog" subtitle="Expert skincare tips, treatment insights, and wellness advice" secondaryButtonText="View Services" secondaryButtonLink="/services" /><section className="sec-porcelain sec-pad"><div className="container"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{posts.map((post, index) => <motion.div key={post.title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: .5, delay: index * .1 }} viewport={{ once: true }} className="group overflow-hidden transition-all h-full" style={{ borderRadius: 'calc(var(--radius) + 8px)', boxShadow: 'var(--shadow-sm)' }}><a href={post.link} target="_blank" rel="noreferrer"><div className="aspect-video overflow-hidden"><img src={post.image} alt={post.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" /></div></a><div className="p-6"><div className="flex flex-wrap gap-3 text-xs mb-3" style={{ color: 'var(--fg-muted)' }}><span className="flex items-center gap-1"><UserRound className="h-3 w-3" /> {post.author}</span><span className="flex items-center gap-1"><CalendarDays className="h-3 w-3" /> {post.date}</span><span className="flex items-center gap-1"><Tag className="h-3 w-3" /> {post.category}</span></div><h3 className="font-heading font-medium text-lg mb-2 group-hover:text-primary transition-colors line-clamp-2">{post.title}</h3><p className="text-sm mb-4 line-clamp-2" style={{ color: 'var(--fg-muted)' }}>{post.excerpt}</p><a href={post.link} target="_blank" rel="noreferrer" className="card-book">Read More <ArrowRight className="ml-2 h-4 w-4" /></a></div></motion.div>)}</div></div></section></Layout>;
}
