import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, Check, ChevronDown, Clock3, Play, ShieldCheck, Sparkles, Target } from 'lucide-react';
import Layout from '../components/Layout';
import PageHero from '../components/PageHero';
import treatments from '../data/treatments.json';
import { Card } from '../components/ui';
import { useBooking } from '../components/BookingModal';

// Each detailed treatment maps to the catalogue category its bookable
// options live under, so the booking card opens pre-filtered to it.
const BOOKING_CATEGORY = {
  'plasma-treatment': 'Face Treatments',
  'hydra-facial': 'Face Treatments',
  'hair-regrowth-therapy': 'Body Treatments',
  'ultraformer-therapy': 'Face Treatments',
  'laser-hair-removal': 'Laser Hair Removal - Ladies',
  'anti-aging-treatment': 'Face Treatments',
  'acne-treatment': 'Face Treatments',
  'cellulite-treatment': 'Body Treatments',
};

function CategoryNav({ active, onChange }) {
  return <div className="relative"><div className="absolute left-0 top-0 bottom-0 w-8 bg-gradient-to-r from-background to-transparent z-10 pointer-events-none" /><div className="absolute right-0 top-0 bottom-0 w-8 bg-gradient-to-l from-background to-transparent z-10 pointer-events-none" /><div className="overflow-x-auto scrollbar-hide py-2 -mx-4 px-4"><div className="flex gap-2 min-w-max">{treatments.map((item) => { const selected = active === item.id; return <button key={item.id} onClick={() => onChange(item.id)} className={`relative px-5 py-2.5 rounded-full text-sm font-medium transition-all duration-300 whitespace-nowrap ${selected ? 'text-primary-foreground bg-gradient-to-r from-primary to-accent shadow-glow' : 'text-muted-foreground hover:text-foreground hover:bg-muted/50'}`}>{item.category}</button>; })}</div></div></div>;
}

function TreatmentDetail({ treatment }) {
  const [openFaq, setOpenFaq] = useState(null);
  const { openBooking } = useBooking();
  const bookThis = () => openBooking({
    category: BOOKING_CATEGORY[treatment.id] || '',
    title: treatment.category,
  });
  return <motion.div id={treatment.id} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} transition={{ duration: .5 }} viewport={{ once: true }} className="scroll-mt-32">
    <div className="grid lg:grid-cols-2 gap-8 lg:gap-12 mb-12">
      <div className="relative aspect-[4/3] lg:aspect-square rounded-3xl overflow-hidden shadow-2xl group">
        {treatment.video ? <video src={treatment.video} className="absolute inset-0 w-full h-full object-cover" autoPlay muted loop playsInline controlsList="nodownload" disablePictureInPicture poster={treatment.image} /> : <img src={treatment.image} alt={treatment.category} className="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-105" />}
        <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" /><div className="absolute inset-0 border-2 border-primary/20 rounded-3xl" />
        {treatment.video && <div className="absolute top-4 left-4 flex items-center gap-2 bg-black/50 backdrop-blur-sm rounded-full px-3 py-1.5"><Play className="w-3 h-3 text-white fill-white" /><span className="text-xs text-white font-medium">Treatment Video</span></div>}
        <div className="absolute bottom-4 left-4 right-4 flex gap-3"><div className="bg-black/60 backdrop-blur-sm rounded-xl px-4 py-2 flex items-center gap-2"><Clock3 className="w-4 h-4 text-primary" /><span className="text-sm text-white">{treatment.duration}</span></div><div className="bg-black/60 backdrop-blur-sm rounded-xl px-4 py-2 flex items-center gap-2"><Target className="w-4 h-4 text-primary" /><span className="text-sm text-white">{treatment.sessionsRecommended}</span></div></div>
      </div>
      <div className="flex flex-col justify-center"><div className="flex items-center gap-2 mb-3"><Sparkles className="w-4 h-4 text-primary" /><span className="text-primary text-sm font-medium uppercase tracking-wider">Professional Treatment</span></div><h2 className="font-heading text-3xl md:text-4xl lg:text-5xl font-semibold mb-3"><span className="text-gradient">{treatment.category}</span></h2><p className="text-lg text-foreground font-medium mb-4">{treatment.tagline}</p><p className="text-muted-foreground text-base leading-relaxed mb-6">{treatment.description}</p><div className="space-y-3 mb-6"><p className="text-muted-foreground italic">{treatment.problem}</p><p className="text-foreground">{treatment.solution}</p></div><div className="flex flex-wrap gap-3"><button type="button" onClick={bookThis} className="inline-flex items-center justify-center h-11 px-8 rounded-full shadow-lg bg-primary text-primary-foreground text-sm font-medium">Book Now <ArrowRight className="ml-2 h-5 w-5" /></button></div></div>
    </div>

    <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><h3 className="font-heading text-2xl md:text-3xl font-semibold mb-6 text-center">How It <span className="text-gradient">Works</span></h3><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{treatment.howItWorks.map((step) => <Card key={step.step} className="relative overflow-hidden rounded-2xl border-border/30 bg-card/80 backdrop-blur-sm hover:shadow-xl transition-all duration-300 hover:-translate-y-1"><div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-primary via-accent to-primary opacity-50" /><div className="p-6"><div className="flex items-center gap-4 mb-3"><div className="w-10 h-10 rounded-full bg-primary/10 border border-primary/30 flex items-center justify-center"><span className="text-primary font-bold">{step.step}</span></div><h4 className="font-semibold text-foreground">{step.title}</h4></div><p className="text-sm text-muted-foreground leading-relaxed">{step.description}</p></div></Card>)}</div></motion.div>

    {treatment.videoEmbed && <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><h3 className="font-heading text-2xl md:text-3xl font-semibold mb-6 text-center">Treatment <span className="text-gradient">Video</span></h3><div className="max-w-4xl mx-auto rounded-3xl overflow-hidden shadow-2xl border border-border/30"><div className="relative w-full" style={{ paddingTop: '56.25%' }} dangerouslySetInnerHTML={{ __html: treatment.videoEmbed }} /></div></motion.div>}

    <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><h3 className="font-heading text-2xl md:text-3xl font-semibold mb-6 text-center">Key <span className="text-gradient">Benefits</span></h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{treatment.benefits.map((benefit) => <div key={benefit} className="flex items-start gap-3 p-4 rounded-2xl bg-card/60 border border-border/30 hover:border-primary/30 transition-colors"><Check className="w-5 h-5 text-primary mt-0.5 flex-shrink-0" /><span className="text-sm text-foreground">{benefit}</span></div>)}</div></motion.div>

    {treatment.beforeAfterImages?.length > 0 && <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><h3 className="font-heading text-2xl md:text-3xl font-semibold mb-6 text-center">Before & <span className="text-gradient">After</span></h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{treatment.beforeAfterImages.map((item) => <figure key={`${item.image}-${item.caption}`} className="rounded-2xl overflow-hidden border border-border/30 bg-card"><img src={item.image} alt={item.caption} className="w-full aspect-square object-cover" /><figcaption className="p-4 text-sm text-muted-foreground">{item.caption}</figcaption></figure>)}</div></motion.div>}

    <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><h3 className="font-heading text-2xl md:text-3xl font-semibold mb-6 text-center"><span className="text-gradient">Pricing</span></h3><Card className="rounded-3xl border-border/30 overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead className="bg-muted/50"><tr><th className="text-left p-4 font-semibold text-foreground">Treatment Area</th><th className="text-center p-4 font-semibold text-foreground">Single Session</th>{treatment.pricing.some((p) => p.package) && <th className="text-center p-4 font-semibold text-foreground">Package</th>}</tr></thead><tbody className="divide-y divide-border/30">{treatment.pricing.map((price, index) => <tr key={`${price.area}-${index}`} className="hover:bg-muted/30 transition-colors"><td className="p-4 text-foreground">{price.area}</td><td className="p-4 text-center"><span className="text-lg font-bold text-gradient">{price.singleSession}</span></td>{treatment.pricing.some((p) => p.package) && <td className="p-4 text-center">{price.package && <div><span className="font-semibold text-foreground">{price.package}</span>{price.packageNote && <span className="block text-xs text-muted-foreground">{price.packageNote}</span>}</div>}</td>}</tr>)}</tbody></table></div></Card></motion.div>

    <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="rounded-3xl border border-primary/20 bg-primary/5 p-6 sm:p-8 text-center"><h3 className="font-heading text-2xl md:text-3xl font-semibold mb-2">Book <span className="text-gradient">{treatment.category}</span></h3><p className="text-muted-foreground mb-5 max-w-xl mx-auto">Pick your option and pay the deposit here — no redirect. Your first treatment is 35% off.</p><button type="button" onClick={bookThis} className="inline-flex items-center justify-center h-11 px-8 rounded-full bg-primary text-primary-foreground text-sm font-medium shadow-lg">Book {treatment.category} <ArrowRight className="ml-2 h-4 w-4" /></button></div></motion.div>

    <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><h3 className="font-heading text-2xl md:text-3xl font-semibold mb-6 text-center">Frequently Asked <span className="text-gradient">Questions</span></h3><Card className="rounded-3xl border-border/30 overflow-hidden">{treatment.faqs.map((faq, index) => <div key={faq.question} className="border-b last:border-b-0 border-border/30"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="w-full px-6 py-4 text-left hover:bg-muted/30 flex items-center justify-between"><span className="font-medium text-foreground pr-4">{faq.question}</span><ChevronDown className={`h-4 w-4 shrink-0 transition-transform duration-200 ${openFaq === index ? 'rotate-180' : ''}`} /></button>{openFaq === index && <div className="px-6 pb-4"><p className="text-muted-foreground leading-relaxed">{faq.answer}</p></div>}</div>)}</Card></motion.div>

    {treatment.safetyInfo && <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-8"><div className="p-6 rounded-3xl bg-muted/50 border border-border/50"><div className="flex items-start gap-4"><ShieldCheck className="w-6 h-6 text-primary flex-shrink-0 mt-0.5" /><div><h4 className="font-semibold text-foreground mb-2">Safety & Care Information</h4><p className="text-sm text-muted-foreground leading-relaxed">{treatment.safetyInfo}</p></div></div></div></motion.div>}

    <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center p-8 rounded-3xl bg-gradient-to-br from-primary/10 via-accent/5 to-primary/10 border border-primary/20"><h4 className="font-heading text-xl md:text-2xl font-semibold mb-3">Ready for Your <span className="text-gradient">{treatment.category}</span> Consultation?</h4><p className="text-muted-foreground mb-6 max-w-lg mx-auto">Book a free consultation to discuss your treatment goals and create a personalized plan.</p><div className="flex flex-wrap gap-3 justify-center"><button type="button" onClick={bookThis} className="inline-flex items-center justify-center h-11 px-8 rounded-full shadow-lg bg-primary text-primary-foreground text-sm font-medium">Book Appointment <ArrowRight className="ml-2 h-5 w-5" /></button></div></motion.div>
  </motion.div>;
}

export default function Services() {
  const [active, setActive] = useState(treatments[0].id);
  const goTo = (id) => { setActive(id); const element = document.getElementById(id); if (element) window.scrollTo({ top: element.getBoundingClientRect().top + window.pageYOffset - 160, behavior: 'smooth' }); };
  useEffect(() => {
    if (window.location.hash) setTimeout(() => goTo(window.location.hash.slice(1)), 100);
    const onScroll = () => { for (const item of treatments) { const element = document.getElementById(item.id); if (element) { const rect = element.getBoundingClientRect(); if (rect.top <= 200 && rect.bottom >= 200) { setActive(item.id); break; } } } };
    window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll);
  }, []);
  return <Layout><PageHero tagline="Professional Treatments" title="Premium Skin Clinic in" titleHighlight="Sandton" subtitle="Science-backed, non-invasive treatments tailored to your unique skin concerns." secondaryButtonText="View Pricing" secondaryButtonLink="/pricing" imageIndex={2} /><section className="py-8 bg-card border-y border-border/50"><div className="container"><div className="max-w-4xl mx-auto text-center"><p className="text-muted-foreground leading-relaxed">DIY treatments and unqualified providers can cause <strong className="text-foreground">burns, scars, and permanent skin damage</strong>. Our medical-grade protocols deliver <strong className="text-primary">safe, science-backed results</strong> you can trust.</p></div></div></section><section className="sticky top-16 z-40 bg-background/95 backdrop-blur-lg border-b border-border/50 py-4"><div className="container"><CategoryNav active={active} onChange={goTo} /></div></section><section className="py-16 lg:py-24"><div className="container space-y-32">{treatments.map((treatment) => <TreatmentDetail key={treatment.id} treatment={treatment} />)}</div></section><section className="py-20 bg-gradient-to-br from-primary via-primary to-accent relative overflow-hidden"><div className="container text-center relative z-10"><h2 className="font-heading text-3xl md:text-4xl lg:text-5xl font-semibold text-primary-foreground mb-6">Ready to Transform Your Skin?</h2><p className="text-primary-foreground/80 text-lg md:text-xl mb-10 max-w-2xl mx-auto">Book a consultation with our skin specialists and get a personalized treatment plan.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><Link to="/booking" className="inline-flex items-center justify-center h-11 px-10 bg-white text-primary rounded-full shadow-2xl text-base">Book Online Now <ArrowRight className="ml-2 h-5 w-5" /></Link></div></div></section></Layout>;
}
